### PR TITLE
Remove ThreadBuildContext

### PR DESCRIPTION
**Pull request by laeubi**
Fix https://github.com/codehaus-plexus/plexus-build-api/issues/45

@olamy can you review?

### CODE REVIEW

**Comment by laeubi** [comment]
All checks passed, can this be merged?

**Comment by olamy** [comment]
> All checks passed, can this be merged?

did you test this will maven plugins using the api?

**Comment by laeubi** [comment]
> did you test this will maven plugins using the api?

I'm not aware of any use for the maven plugin, this is used in m2e on the implementation side, but as explained in #45 I don't think an API should ship "helpers" if the implementation could implement it itself.

**Comment by olamy** [comment]
there are https://github.com/search?q=org%3Aapache+ThreadBuildContext&type=code

**Comment by laeubi** [comment]
Both use it for testing purpose, one of the projects is archived. And for the later one I wonder why they do not register `TestIncrementalBuildContext` at first place and have the constructor parameter be threadlocals ...

**Comment by olamy** [comment]
All good for the (good :) ) answers!

**Pull request merged**
