### PR TITLE
change package to org.codehaus.plexus.build

### PR DESCRIPTION
**Pull request by olamy**
- change package name to org.codehaus.plexus.build.incremental

### CODE REVIEW

**Comment by laeubi** [comment]
Can we maybe change the package to org.codehaus.plexus.build.**api** instead? that would better match the name and incremental is only one aspect here and might confuse people with [maven-incremental-builds](https://cwiki.apache.org/confluence/display/MAVEN/Incremental+Builds) ..

**Comment by olamy** [comment]
> Can we maybe change the package to org.codehaus.plexus.build.**api** instead? that would better match the name and incremental is only one aspect here and might confuse people with [maven-incremental-builds](https://cwiki.apache.org/confluence/display/MAVEN/Incremental+Builds) ..

good idea

**Comment by olamy** [comment]
done

**Review by laeubi — APPROVED** [review]
LGTM

**Review by slachiewicz — APPROVED** [review]

**Pull request merged**
