### PR TITLE
Use a CachingOutputStream when using the build context

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by laeubi** [comment]
@gnodet can you explain what will be the advantage here?

**Comment by gnodet** [comment]
> @gnodet can you explain what will be the advantage here?

It provides caching.  The output file is not modified unless there's an actual change in the content.
My final goal is to have most plugins behave nicely when nothing has changed, so that jars are not modified, as it has a cascading effects in big reactor projects and cause a lot of rebuilds for nothing.

**Comment by laeubi** [comment]
Maybe you can adjust the commit message to explain this as it is not really obvious (for me) so one can read about it later on. I must confess the name is a bit confusing because one usually more have caching for *reading* data.

**Review by laeubi — APPROVED** [review]
Looks good, but keep in mind that as of today no one is using the "new" build API here so a release might not have any impact on existing users.

**Review by kwin — APPROVED** [review]

**Comment by gnodet** [comment]
> > > Looks good, but keep in mind that as of today no one is using the "new" build API here so a release might not have any impact on existing users.
> > 
> > 
> > Yes, PRs will follow...
> 
> This won't help as this will instantly break the plugin, first m2e needs to add support for the new plexus-build API ...

Plugins won't be broken, I think it's only the _incremental_ build inside m2e which will be broken, and most probably, not really broken, but running sub-optimally (i.e. will rebuild more than needed) until m2e is update to support both.

**Comment by laeubi** [comment]
> Plugins won't be broken, I think it's only the incremental build inside m2e which will be broken, and most probably, not really broken, but running sub-optimally (i.e. will rebuild more than needed) until m2e is update to support both.

Well that's the purpose of the build-api if that is not working the plugin is (from user POV) broken...

**Pull request merged**
