### PR TITLE
Inline EmptyScanner into build context

### PR DESCRIPTION
**Pull request by laeubi**
EmptyScanner is actually only used (and useful) in the DefaultBuildContext and should be a private final inner class to not blow the API that needs to be maintained.

Fix https://github.com/codehaus-plexus/plexus-build-api/issues/46

### CODE REVIEW

**Comment by laeubi** [comment]
@olamy can you review?

**Comment by kwin** [comment]
A bit dangerous as consumers could have used `EmptyScanner` (for whatever reason). I wouldn't touch the API here just for cleanup purposes...

**Comment by laeubi** [comment]
This API is actually used nowhere else as it has a new group ID and m2e was the only provider here and there is no use for the empty scanner there.

And exactly for "consumers could have used EmptyScanner (for whatever reason)" I like to get rid of it for the new API (probably even get rid of scanner at all).

**Comment by kwin** [comment]
Even though the coordinates have changed I would rather keep the API backwards compatible to ease updates. A new API 2.0 should rather be developed in Maven 4….

**Pull request closed without merging**
